### PR TITLE
Mpw 7

### PR DESCRIPTION
**Pull request by marwaneltoukhy**
- Changed magicrc to be taken from the PDK
- Added 3 environment variables
  - `LVS_ROOT`: Root of directory to run lvs from (default to pwd)
  - `LOG_ROOT`: Root of directory to write logs to (default to pwd)
  - `LOG_ROOT`: Root of directory to write reports to (default to pwd)

### CODE REVIEW

**Comment by d-m-bailey** [comment]
Thanks for the suggestions. 

@marwaneltoukhy `flatglob`, `abstract`, `flatten`, and `noflatten` may be different for different blocks, so we may not want to use `$LVS_ROOT` for those. Maybe copy the default version from `$LVS_ROOT` with a warning if the file does not exist in the current directory.

Is it ok to keep the extract directory in the current directory or would you like a override for that too (ie. WORK_DIR)?

**Comment by marwaneltoukhy** [comment]
> @marwaneltoukhy flatglob, abstract, flatten, and noflatten may be different for different blocks, so we may not want to use $LVS_ROOT for those. Maybe copy the default version from $LVS_ROOT with a warning if the file does not exist in the current directory.

I don't really understand this part, `$LVS_ROOT` should basically be the path to this repo in the file system. Maybe the name of the variable isn't straight forward, we can change it to `$BE_CHECKS_ROOT` for example.

Also, I was trying to think of a more automatic way of writing the `flatglob`, `abstract`, `flatten`, and `noflatten` is that possible or are we going to have to rewrite it every time we do LVS for a different block?

I don't mind the extract directory staying at the same place, but we can add a global variable for it as well so that in the future if we want to change it, it would be easy

**Comment by d-m-bailey** [comment]
> I don't really understand this part, $LVS_ROOT should basically be the path to this repo in the file system. Maybe the name of the variable isn't straight forward, we can change it to $BE_CHECKS_ROOT for example.

`$LVS_ROOT` is fine. It's just that `flatglob`, `abstract`, `flatten`, and `noflatten` aren't necessarily the same for every block or process.

> Also, I was trying to think of a more automatic way of writing the flatglob, abstract, flatten, and noflatten is that possible or are we going to have to rewrite it every time we do LVS for a different block?

I think we should give the users a default and let them modify as needed.

**Comment by d-m-bailey** [comment]
@marwaneltoukhy I incorporated most of these suggestions in another branch, so I'm going to close this.

**Pull request closed without merging**
